desy-ml/cheetah

- cheetah/accelerator.py
> Fix variable naming for misalignment treatment

- .github/workflows/formatting.yml
- .pre-commit-config.yaml
- README.md
- benchmark/astra/ARESlatticeStage3v1_9.py
- benchmark/cheetah/ARESlatticeStage3v1_9.py
- benchmark/ocelot/ARESlatticeStage3v1_9.py
- test/ARESlatticeStage3v1_9.py
- test/speed_comparison.py
Add black and isort checking for CI/CD pipeline
Add pre-commit hooks and updated README.md
> Add formatting check

- .flake8
- .github/workflows/formatting.yml
- .pre-commit-config.yaml
- benchmark/astra/ARESlatticeStage3v1_9.py
- benchmark/cheetah/ARESlatticeStage3v1_9.py
- benchmark/ocelot/ARESlatticeStage3v1_9.py
- cheetah/__init__.py
- cheetah/utils.py
- test/ARESlatticeStage3v1_9.py
- test/speed_comparison.py
Add flake8 check in CI/CD and pre-commit configuration.
Modified some files to pass the pipeline.
> Add flake8 linting

- cheetah/accelerator.py
- cheetah/particles.py
- setup.py
This pull request is going to specifically adress issue #2 .
-The pull request introduces a new comment on the 'init' function. This will help finding the definitions for the parameters.
-Also a new comment on the 'transfer_map' function has been added, explaining the general purpose as well as the state vector and parameters, returns and raises.
-The parameter 'energy' has been removed from various classes. The parameter 'energy' is passed on through the beam passed to the segment. It is therefore not changeable by the user, when trying to control the beam, e.g. you can't call the function HorizontalCorrector and pass a parameter energy to this function. This parameter is defined, when the beam is fed in the Segment.
-'repr' has now a short comment describing the use of this function. …
> Improved documentation

- cheetah/accelerator.py
- cheetah/particles.py
- cheetah/track_methods.py
- cheetah/utils.py
- docs/accelerator.rst
- docs/conf.py
- docs/index.rst
- docs/particles.rst
- docs/track_methods.rst
- docs/utils.rst
A further pull request addressing #2. Adds the Sphinx autodoc extension that automatically generates parts of the documentation for all the classes and functions from their docstrings.
> Add Sphinx autodoc

- .github/workflows/format.yml
- .github/workflows/pytest.yml
- README.md
Add some badges. Unfortunately, I didn't get a coverage badge to work.
> Add badges

- cheetah/particles.py
- tests/test_ocelot_import.py
- Fix the charge conversion in `from_ocelot`
- Add test functions for from_ocelot methods
> Fix the charge conversion in `from_ocelot`

- CHANGELOG.md
- cheetah/accelerator.py
- cheetah/converters/nocelot.py
- tests/test_compare_ocelot.py
Fix fringe_integral_exit not used bug;
Update tests and ocelot converters acoordingly.
> Fix #98; Fix `fringe_instegral_exit` not used bug

- CHANGELOG.md
- cheetah/accelerator.py
- tests/test_bpm.py
> 101 error when using bpm with parameter beam

- CHANGELOG.md
> Advance changelog to successor of `v0.6.2` release

- CHANGELOG.md
- LICENSE
- README.md
Add GPL 3 license to the project.
A license will make it easier for people to use Cheetah and know what the can and cannot do.  Fixes #130.
> Add a license

- LICENSE
> Change license from AGPL 3 to GPL 3

- CHANGELOG.md
- cheetah/accelerator.py
- tests/test_compare_ocelot.py
Fixed a typo in the cavity `_track_beam` method. It should produce correct result now.
> Another fix to the cavity tracking, removed large tolerance in the ocelot benchmark test

- CHANGELOG.md
> Small fix to changelog

- .pre-commit-config.yaml
- CHANGELOG.md
Update alle versions in `.pre-commit-config.yaml`.
Closes #147.
> Update pre-commit config

- cheetah/particles.py
- tests/test_particle_beam.py
The title says it all.
Closes #155.
> Fix ellipsoid spelling error

- .vscode/ltex.dictionary.en-GB.txt
- CHANGELOG.md
- CITATION.bib
- README.md
- docs/index.rst
Updates all the references for how we would like to be cited to the new PRAB publication..
The PRAB publication was just released.
> Update reference from arXiv preprint to PRAB publication

- README.md
> Fix non-vectorised assignment typo in README

- CHANGELOG.md
- README.md
Add imports to the code examples in the README.
Makes sure the code example is complete and runs as it is.
> Add imports to code example in the README

- CHANGELOG.md
- cheetah/accelerator/aperture.py
- cheetah/accelerator/bpm.py
- cheetah/accelerator/cavity.py
- cheetah/accelerator/custom_transfer_map.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/drift.py
- cheetah/accelerator/element.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/marker.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/rbend.py
- cheetah/accelerator/screen.py
- cheetah/accelerator/segment.py
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/undulator.py
- cheetah/accelerator/vertical_corrector.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- cheetah/track_methods.py
In many files there were two identical constants for the electron mass. The duplication is removed and unused imports are deleted.
Closes #179
> Unify constants for electron mass

- test_requirements.txt
Use a custom non-breaking ocelot fork in tests until the PR in ocelot (https://github.com/ocelot-collab/ocelot/pull/256) is merged.
> Update `test_requirements.txt` to use a custom fixed ocelot version

- CHANGELOG.md
- cheetah/accelerator/quadrupole.py
The units of the quadrupole strength were wrong, changed from `rad/m` to `1/m^2`
Both units are very common, so it's important that the documentation reflects the correct ones, specially for developers working on new converters :)
> Update docstring of quadrupole.py

- CHANGELOG.md
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/undulator.py
- tests/test_vectorized.py
The `Undulator` and `Solendoid` are currently failing to track in vectorized form.
> Fix vectorization in Undulator and Solenoid

- .github/workflows/format.yaml
- .github/workflows/pytest.yaml
- CHANGELOG.md
Adds a more restrictive `on` configuration to GitHub Actions. These are copied from the[Stable Baselines3 repository](https://github.com/DLR-RM/stable-baselines3/blob/master/.github/workflows/ci.yml).
This change halts the number of runs performed in each PR, because previously each run was triggered twice. Consequentially, the time taken for automatic testing etc. is effectively halved.
> Prevent GitHub Actions from running twice every time

- CHANGELOG.md
- README.md
Fixes the way the Cheetah logo is displayed in the README by moving its HTML tag and adding a longer introduction to prevent the heading lines from crossing the image.
This broke increasingly with changes to GitHub's Markdown renderer.
> Fix Cheetah README image display

- cheetah/latticejson.py
Updates the Cheetah version the LatticeJSON exporter writes to the new `0.7`. (Should not need a changelog entry.)
Addresses #257.
> Update LatticeJSON version tag

- .github/workflows/pytest.yaml
- .readthedocs.yaml
- CHANGELOG.md
- setup.py
This PR drops support for Python 3.9 primarily by removing it from the test pipeline. This does not mean that compatibility is immediately broken, but that we will no longer make sure it works.
Closes #205. Following NumPy guidelines packages should have started dropping 3.9 support late last year. PyDOOCS no longer requires 3.9, so from our side this is no longer blocking.
> Drop Python 3.9 support

- CHANGELOG.md
- cheetah/converters/elegant.py
- cheetah/converters/utils/fortran_namelist.py
- tests/resources/fodo.lte
Recognises alternative names `marker`, `quadrupole` and `csbend` when parsing Elegant lattices and allows spaces before commas in Fortran Namelists when defining elements by adapting the corresponding regex.
Adds some elements encountered when parsing the DESY R-Weg lattice and fixes #326.
> Add new elements to Elegant import

- CHANGELOG.md
- tests/test_space_charge_kick.py
Doc change only.
Although we originally thought about using the ConstF channel example, we used the simpler expanding beam in free space due to a lack of const. focusing element.
Follow-up to #142
> Doc: ImpactX Example (Space Charge)

- CHANGELOG.md
- tests/test_space_charge_kick.py
> Fix minor issues previous from previous PRs

- CHANGELOG.md
- README.md
- docs/index.rst
- tests/test_space_charge_kick.py
Adds an invitation link to the new Discord server to the README and documentation home page.
The Discord server should allow for less formal discussions that don't necessarily fit the Issues on GitHub.
> Add link to the new Cheetah Discord server

- CHANGELOG.md
- README.md
Replaces the invite link to the Cheetah Discord server with one that doesn't have an expiration date.
The original link had an expiration date and was expired.
> Fix Discord server link to one without expiration

- CHANGELOG.md
- README.md
Adds a badge that shows the number of downloads from PyPI per month.
> Add a badge with the PyPI downloads

- CHANGELOG.md
- docs/conf.py
> Prepare 0.7.1 release

- CHANGELOG.md
- setup.py
Temporarily limit torch dependency to 2.6 or lower to avoid abort trap: 6 error with 2.7 (at least on macOS).
All GitHub Actions are failing because of issues with PyTorch 2.7.
> Temporarily limit `torch` dependency to `2.6` or lower to avoid `abort trap: 6` error with `2.7` (at least on macOS)

- CHANGELOG.md
- docs/conf.py
- setup.py
> Housekeeping for `v0.7.2` release

- CHANGELOG.md
- docs/requirements.txt
> Unpin `snowpallstemmer`

- CHANGELOG.md
- setup.py
Sets Cheetah to require `torch>=2.3`.
Cheetah uses methods not available in earlier versions of `torch`. Specifically, `torch.get_default_device()` and `torch.get_default_dtype()`.
> Fix minimum version of PyTorch compatible with Cheetah

- CHANGELOG.md
- docs/conf.py
- setup.py
> Housekeeping for 0.7.3 release

- CHANGELOG.md
- cheetah/converters/utils/fortran_namelist.py
- cheetah/converters/utils/infix.py
- tests/test_infix.py
Implements an infix parser (shunting yard algorithm to AST) for Bmad/Elegant. 
This fixes a potential security issue with calling `eval()` on user input and allows for more robust parsing of lattice files.
Closes #412 
> Infix parser

- CHANGELOG.md
- cheetah/accelerator/element.py
- cheetah/converters/elegant.py
Couple missing parameter pass-throughs of `sanitize_names`
> couple missed sanitize_name params

- .vscode/ltex.dictionary.en-GB.txt
- CHANGELOG.md
> Qucik fix adding @adhamrait as first time contributor

- CHANGELOG.md
- cheetah/__init__.py
Makes warning classes available in the top-level namespace so that they can be references as e.g. `cheetah.PhysicsWarning` to shorted `filterwarnigns` code.
Closes #478.
> Make warnings available in top-level namespace

- CHANGELOG.md
- tests/resources/bmad_tutorial_lattice.bmad
- tests/test_bmad_conversion.py
Add the ability to the Bmad converter (and possibly Elegant as well?) to parse expressions that access properties from other elements, e.g.
```
v: drift, l = -q[l]
```
Closes #479.
> Add element property access to the Bmad converter

- CHANGELOG.md
- test_requirements.txt
- tests/test_compare_ocelot.py
Temporarily sets the commit of the Ocelot repository used for some comparison tests to the last commit that didn't fail the Ocelot comparison tests.
Ocelot released a new version 25.x.x with which the comparison tests fail. Related to, but doesn't finally close #512. Temporary stand-in for permanent fix #513 such that other PRs can move ahead.
> Temporarily fix Ocelot test dependency to old 24.x.x commit where tests still pass

- .vscode/ltex.dictionary.en-GB.txt
- CHANGELOG.md
- README.md
- cheetah/utils/cache.py
- docs/index.rst
Upgrades to `v1.0.2` of the 3D assets repository and gives credit to Suchet for his parti in the implementation.
> Upgrade to new release of 3D assets with flipped horizontal corrector and fix credit

- CHANGELOG.md
- cheetah/particles/beam.py
- cheetah/particles/particle_beam.py
- test_requirements.txt
- tests/test_compare_ocelot.py
Changes the Ocelot dependency from the `master` branch of the Ocelot GitHub repository to its new PyPI release. Fixes tests that use old interface of Ocelot, and increases tolerances on tests where needed.
Closes #512.
> Fix Ocelot-related tests failing

- CHANGELOG.md
- cheetah/accelerator/segment.py
- cheetah/converters/elegant.py
> Fix typo saying Bmad in Elegant import method docstring

- CHANGELOG.md
- cheetah/accelerator/segment.py
- tests/test_segment.py
Adds property that lists the element names as well as a method that returns element index for a given element name.
> Methods for getting the element names / indices for segment

- .github/workflows/format.yaml
- CHANGELOG.md
Reintroduce `flake8-black` to `format` Action after `BLK900` issue was fixed by them.
Reverts #569. Closes #568.
> Reintroduce `flake8-black` after `BLK900` issue was fixed by them
