- cheetah/utils.py
Fixes #16. Changes the pattern to `"BSC"` which is present in AREABSCR1 and in ARBCBSCE1 and therefore likely going to be more reliable.
> Fix screen conversion with ARBCBSCE1

- .readthedocs.yaml
Broken dependencies caused autodoc to not document the items in each of the modules when building on readthedocs. This should be fixed with this pull request.
> Fix dependencies on readthedocs

- cheetah/particles.py
- setup.py
- test/test_astra_import.py
- test/test_compare_ocelot.py
- test/test_parameter_beam.py
- test/test_particle_beam.py
Adding twiss parameters of properties of the `Beam` class. This way they can easily be a computed from tracked `ParameterBeam` and `ParticleBeam`.
> Add twiss parameter calculations

- cheetah/accelerator.py
- cheetah/particles.py
- Now one can also specify the `device` for ParameterBeam
- Added the according option in the doc string
- Fixed the Element.__call__ device check
> Add device option for ParameterBeam

- CHANGELOG.md
- cheetah/accelerator.py
- cheetah/track_methods.py
- tests/test_compare_ocelot.py
- Fix the R_56 component of the transfer map in `Drift`;
- Updated the test functions, now the difference should be less.
- Add R_56 component in `VerticalCorrector` and `HorizontalCorrector`
- Fix the edge focusing transfer maps for bends (e.g. `Dipole` `RBend` and `SBend`)
- Removed the large tolerances for result comparison in test functions
> Fix the transfer map of `Drift` and edge focusing of `Dipole`

- README.md
Change the `.yml` file endings in the badge links to `.yaml`.
The links were broken in a recent change when the file endings of the workflows were changed(#104).
> Fix links to format and pytest badges

- CHANGELOG.md
- cheetah/particles.py
- tests/test_astra_import.py
Convert the dtype of `energy` to `torch.float32` in the conversion from an ASTRA beam.
Cheetah should use `torch.float32` internally (for now). Fixes #110.
> Fix ASTRA beam import energy dtype

- CHANGELOG.md
- cheetah/accelerator.py
- cheetah/track_methods.py
- tests/test_compare_beam_type.py
Fixes the `__repr__` bug in `Cavity` as found in #120.
Closes #120.
> Fix cavity `__repr__` printing volate for phase

- CHANGELOG.md
- cheetah/accelerator.py
- cheetah/particles.py
Improve the docstring, make sure the units for the phase space dimensions are correct now.
> Correct wrong units in docstring in multiple locations

- CHANGELOG.md
- docs/index.rst
Links to the new differentiable Cheetah paper on arXiv, rather than the old IPAC paper, which is not up-to-date with Cheetah as it is now.
The new paper matches Cheetah today much more closer and should now be considered the main reference.
> Link to the new paper (on arXiv) in the documentation

- CHANGELOG.md
- cheetah/accelerator.py
- tests/test_compare_ocelot.py
- Fixed the cavity transfer map, now tracking `s` and `p` components correctly
- Update CHANGELOG.md
> Fix cavity transfer map

- CHANGELOG.md
- cheetah/accelerator.py
`_track_beam` in `Cavity` received `ParticleBeam` instead of `Beam`. Closes #150.
> 150 fix cavity tracking

- .github/workflows/pytest.yaml
- CHANGELOG.md
Adds Python 3.12 support. It turns out Cheetah already works just fine with 3.12, so all this PR does it add the pytest run with 3.12 to the GitHub Actions.
Python 3.12 was already released half a year ago, so this was overdue.
> Add Python 3.12 support

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- tests/test_dipole.py
A bug fix related to #100 for dipole tracking.
> Fix dipole tracking issue; Add tests accordingly

- CHANGELOG.md
- cheetah/accelerator/cavity.py
- tests/test_compare_ocelot.py
- Fix a missing sign in the cavity tracking method (v0.6.3 was not affected. This was introduced somewhere in the batched execution upgrade #116, but remains unidentified as the test was still passing with some rtol)
- Remove large rtols in the related test as they are no longer required.
- Add an additional test identifying the issue with non-zero RF phase
> Fix cavity tracking issue introduced in recent updates

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- cheetah/accelerator/rbend.py
- tests/test_compare_ocelot.py
- Fix #171 . The `RBend` construction method was not properly updated with the vectorization feature #116 
- Fix a comment in `Dipole` to clearly mention that by default a sector bend is generated.
> Fix vectorization issue in rbend

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- tests/test_dipole.py
Removes an unnecessary name assignment within the `dipole` element to ensure all accelerator elements are assigned unique names if none are provided.
Closes #181 
> Ensure dipoles get a unique name

- .vscode/settings.json
- CHANGELOG.md
- cheetah/accelerator/segment.py
- cheetah/converters/bmad.py
- tests/test_bmad_conversion.py
Makes sure that `device` can be passed to the element initialisations when using `Segment.from_bmad`.
This is needed to be able to load Bmad lattices on a device other than `"cpu"`. Closes #195.
> Implement Bmad conversion device passing

- CHANGELOG.md
- cheetah/accelerator/cavity.py
- cheetah/accelerator/dipole.py
Fix the remaining issues for `is_active` in `Cavity` and `Dipole` for the batched execution. Follow up on the ealier fixes #170, #172, #173
> Fix `is_active` check issue in cavity and dipole

- CHANGELOG.md
- cheetah/accelerator/drift.py
Adding `name` to `Drift` element.
When Cheetah does not recognize an element it transforms it to a `Drift` of the corresponding length to keep the correct element positions. It is useful to have the element name attached to the `Drift` in case the original one was not a drift, for better understanding of the lattice when inspecting the `Segment`.
> Drift name

- CHANGELOG.md
- cheetah/accelerator/segment.py
- cheetah/converters/bmad.py
- cheetah/particles/beam.py
- cheetah/particles/parameter_beam.py
- tests/test_bmad_conversion.py
- tests/test_parameter_beam.py
- tests/test_speed_optimizations.py
Let's users pass the `dtype` when creating a `Segment` from a Bmad lattice.
Also fixes a bug where passing `dtype` to `ParameterBeam.from_twiss` had no effect.
Solves #204. Related to #195 and #196.
> Add `dtype` passing to Bmad `Segment` import

- CHANGELOG.md
- cheetah/accelerator/aperture.py
- cheetah/accelerator/cavity.py
- cheetah/accelerator/custom_transfer_map.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/drift.py
- cheetah/accelerator/element.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/screen.py
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/space_charge_kick.py
- cheetah/accelerator/undulator.py
- cheetah/accelerator/vertical_corrector.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- tests/test_device_dtype.py
Implements that elements and beams can easily be moved to different devices and their beam types can be changes, like you would expect from a normal `torch.nn.Module`.
This is normal for `torch.nn.Module` and would make working with different devices and dtypes in Cheetah much easier. Closes #113.
> Implement moving to `device` and changing `dtype`

- CHANGELOG.md
- cheetah/accelerator/drift.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/segment.py
- cheetah/accelerator/vertical_corrector.py
- tests/test_split.py
Makes sure that when calling `split` on an `Element`, the resulting splits have the same `dtype` as the original `Element`.
This solves an issue when using `Segment.plot_overview` with elements or incoming beams that are not `torch.float32`.
> Fix `dtype` preservation on `split`

- CHANGELOG.md
- cheetah/accelerator/aperture.py
- cheetah/accelerator/cavity.py
- cheetah/accelerator/custom_transfer_map.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/drift.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/screen.py
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/space_charge_kick.py
- cheetah/accelerator/undulator.py
- cheetah/accelerator/vertical_corrector.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- tests/test_vectorized.py
Now broadcasting elements and beams will keep the dtype and device
> Let broadcast keep the dtype and device

- CHANGELOG.md
- cheetah/accelerator/cavity.py
- tests/test_cavity.py
Re-adds the use of `base_rmatrix` for `Cavity`s with `voltage=0.0` because the usually cavity matrix breaks in that case. This was originally removed with the vectorisation because it was difficult to integrate and though to be unnecessary.
Closes #214.
> Fix `Cavity` being broken by vectorisation

- CHANGELOG.md
- cheetah/accelerator/drift.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/vertical_corrector.py
- tests/test_split.py
The current split implementation is not vectorized and fails on vectorized elements
The implementation is changed to treat `resolution` as an upper bound on the length of the resulting subelements. This ensures that the elements will be divided into equally many subelements, even if the vectorized lengths are different.
Because of this change, the subelements are now assigned uniform length, instead of having the final element fill the gap to the total length. This could be considered to be a __breaking change__, but most likely no one relied on that exact behaviour.
> Implement vectorized split

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- tests/test_dipole.py
This PR adds a focussing moment to dipole magnets.
In the course of implementing the elegant lattice converter, one encouters sector bending magnets that feature both a bending angle and a focussing strength. Currently, there is no way to map these magnets into Cheetah `element`.
> Add dipole beam focussing

- CHANGELOG.md
- cheetah/accelerator/rbend.py
- tests/test_dipole.py
Since the `RBend` is inheriting much of the `Dipole` implementation, #235 broke its broadcasting by introducing additional constructor arguments. This PR restores parity between the element constructors, fixing the inherited broadcasting method.
> Fix RBend broadcasting issue

- CHANGELOG.md
- cheetah/converters/bmad.py
Fix the issue hgap -> gap in bmad dipole conversion.
Closes #259.
> Corretly convert hgap in dipole from bmad

- CHANGELOG.md
- cheetah/accelerator/transverse_deflecting_cavity.py
- tests/test_transverse_deflecting_cavity.py
Adds some missing dimensional expansions in the `TransverseDeflectingCavity` code to fix a bug with some vectorisation setups.
Fixes #270.
> Fix vectorized tracking for `TransverseDeflectingCavity`

- CHANGELOG.md
- cheetah/particles/beam.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
The outdated docstrings and properties are adjusted to match the new naming scheme.
In addition, `Beam` is converted into an abstract class, increasing the probability to catch such issues early.
(The old `mu_s` property of `Beam` is renamed to `mu_tau`.)
The beam coordinate system has been adjusted recently, leaving some outdated docstrings in the `Beam` class and its subclasses `ParameterBeam` and `ParticleBeam`.
- #238 
- #279 
> Improve `Beam` docstrings and type hints

- CHANGELOG.md
- cheetah/accelerator/segment.py
- tests/test_plotting.py
The Cheetah plotting routines currently fail if `require_grad=True` is set for any of the involved tensors. The fix is to call `tensor.detach()` before calling matplotlib.
- Closes #287 
> Fix plotting for segments with tensors that require gradients

- README.md
The argument name for  the incoming beam in `Segment.plot_overview` was changed from `beam` to `incoming`, but in a recent PR not updated in the README. This is what is done here.
Fixes #256. Is a continuation of #266.
> Fix wrong argument name in README

- CHANGELOG.md
- cheetah/accelerator/transverse_deflecting_cavity.py
- tests/test_transverse_deflecting_cavity.py
Implements a temporary fix that prevents inactive `TransverseDeflectingCavity`s to take part in transfer map reduction.
Ideally, this should be fixed properly at some point to allow for fast tracking by implementing the `transfer_map` function or inheriting it from `Drift` in the future, to make sure this part of Cheetah is also as fast as it can be. For now the workaround for being fast is to replace inactive elements with `Drift` using the respective functions in `Segment` for doing exactly that.
Calling `transfer_map` on `TransverseDeflectingCavity` would cause a `NotImplementedError` to be raised and therefore prevent tracking through any `Segment` that had an inactive `TransverseDeflectingCavity` in it.
Fixes #290.
> Temporary fix for broken inactive`TransverseDeflectingCavity` in `Segment`

- CHANGELOG.md
- cheetah/particles/beam.py
`Beam` currently shadows `torch.nn.Module.parameters()`, completely changing its behaviour. This PR removes the custom implementation and is therefore a breaking change.
- Closes #282
> Prevent shadowing of `parameters` method in Beam

- CHANGELOG.md
- tests/test_drift.py
It was previously observed that `Element.length` cannot be set to `torch.nn.Parameter` instead of `torch.Tensor`. However, up-to-date version of Cheetah do already support such an assignment.
It is likely that the required change was introduced in 383ff83. To prevent the issue from reappearing, we implement a simple test case.
- Closes #164
> Add test for using `nn.Parameter` as element length

- CHANGELOG.md
- cheetah/accelerator/aperture.py
- cheetah/accelerator/cavity.py
- cheetah/accelerator/custom_transfer_map.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/drift.py
- cheetah/accelerator/element.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/screen.py
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/space_charge_kick.py
- cheetah/accelerator/transverse_deflecting_cavity.py
- cheetah/accelerator/undulator.py
- cheetah/accelerator/vertical_corrector.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- tests/test_differentiable.py
- tests/test_dipole.py
Currently, a `torch.nn.Parameter` provided at initialization to Cheetah elements does not appear in the list of parameters returned by `.parameters()`, in contrast to a parameter assigned after initialization. This PR makes the behaviour consistent.
- Closes #302 
> Fix `nn.Parameter` assignment at initialization

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/vertical_corrector.py
PyTorch currently prints a warning in `Dipole` that `tensor.clone()` should be called explicitly instead of using `torch.tensor`. However, the cloning is unintentional, therefore the calls can rather be replaced by `torch.as_tensor`.
Furthermore, NumPy warns about an internal deprecation. This was raised in #307.
> Fix warnings in test suite

- CHANGELOG.md
- cheetah/accelerator/segment.py
`Segment.plot_overview` currently marks its `incoming` argument as optional with default `None`. This is misleading, since the function crashes if no `Beam` is passed.
This is a breaking change, since the order of arguments has to be changed to allow for `incoming` to have no default.
- Closes #315 
> Make beam argument mandatory in `Segment.plot_overview`

- CHANGELOG.md
- pyproject.toml
Adds a `pyproject.toml` to support the modern editable build mode and configure `setuptools` as the build system.
Closes #245.
> Add `pyproject.toml` for compatability with pip 25

- CHANGELOG.md
- cheetah/particles/beam.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- tests/test_parameter_beam.py
- tests/test_particle_beam.py
Adds methods to `ParameterBeam` and `ParticleBeam` for convenient conversion from one to the other.
As part of this change, longitudinal `mu`s are added to the different beam interfaces, and the covariance property names are unified from names like `cor_x` and `sigma_xpx` to `cov_x`.
It's inconvenient to do this by hand.
Also closes #332 as a related side project.
> Implement converters between `ParameterBeam` and `ParticleBeam`

- CHANGELOG.md
- tests/test_space_charge_kick.py
This PR improves the space-charge tests:
- It now tests the accuracy of the gradient calculation, for the backward-mode differentiation.
- In addition, it adds a similar test for forward-mode differentiation.
Since Cheetah is built with `pytorch`, it supports backward-differentiation, but also forward differentiation (see [this page](https://pytorch.org/tutorials/intermediate/forward_ad_usage.html)). This could be useful since the scaling of forward differentiation is different from that of backward differentiation. 
In addition, previous tests of backward-differentiation mode were simply checking that the differentiation ran without error, but they did not check the accuracy of the computed gradient. In this PR, we now test the accuracy of the gradient, by reusing the parameters of …
> Space charge tests: improve backward-mode test ; add forward-mode test

- CHANGELOG.md
- README.md
- docs/examples/simple.ipynb
In #316, the `incoming` argument of the remaining plotting functions was made mandatory. However, this change was not reflected in the documentation.
> Reflect required beam argument in readme and documentation

- CHANGELOG.md
- cheetah/accelerator/screen.py
- cheetah/accelerator/segment.py
- cheetah/converters/astra.py
- cheetah/converters/bmad.py
- cheetah/converters/elegant.py
- cheetah/converters/ocelot.py
- cheetah/latticejson.py
- cheetah/particles/beam.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- tests/conftest.py
- tests/test_astra_import.py
- tests/test_bmad_conversion.py
- tests/test_compare_ocelot.py
- tests/test_elegant_conversion.py
- tests/test_lattice_json.py
- tests/test_ocelot_import.py
> Automatically detect default `dtype` for lattice and beam importers

- CHANGELOG.md
- cheetah/accelerator/segment.py
- tests/test_segment.py
The current implementation of the `Segment.subcell` method does not allow for open `start` or `end` elements. Furthermore, `end` is always included in the subcell, making it cumbersome to slice a segment into multiple disjunct cells.
This PR increases the flexibility the method by making `start` and `end` optional. The additional optional `endpoint` argument allows to exclude `end` from the created subcell.
- Closes #349 
> Make `Segment.subcell` method more flexible

- CHANGELOG.md
- cheetah/accelerator/dipole.py
> Fix typo that said "quadrupole" in a dipole docstring

- CHANGELOG.md
- cheetah/__init__.py
- cheetah/accelerator/cavity.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/horizontal_corrector.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/solenoid.py
- cheetah/accelerator/transverse_deflecting_cavity.py
- cheetah/accelerator/vertical_corrector.py
- tests/test_elements.py
Adds a test that checks that `is_active` (if an element has it) and `is_skippable` are always properties and of boolean type. Some elements require some arguments to be passed, so the test is designed to fail when a new element is added, such that properly extending the test for that element cannot be forgotten.
Fixes #345, where the `@property` decorator was missing on `Solenoid.is_skippable`.
> Fix `is_active` and `is_skippable` of some elements not being boolean properties

- CHANGELOG.md
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
Assume more reasonable default values for `total_charge` in both beam classes.
Fixes #370.
> Assume more reasonable default values for `total_charge`

- CHANGELOG.md
- cheetah/accelerator/aperture.py
- cheetah/accelerator/dipole.py
- cheetah/accelerator/drift.py
- cheetah/accelerator/element.py
- cheetah/accelerator/quadrupole.py
- cheetah/accelerator/space_charge_kick.py
- cheetah/accelerator/transverse_deflecting_cavity.py
- cheetah/particles/parameter_beam.py
- cheetah/particles/particle_beam.py
- cheetah/particles/species.py
- tests/test_clone.py
Passes `species` in both beam classes `clone` method as well as to various `track` methods.
Fixes #368 and fixes #371.
> Add `species` to cloning of both beam classes

- CHANGELOG.md
- cheetah/accelerator/quadrupole.py
- tests/test_quadrupole.py
Closes #403 
The issue was that the `clone()` method in the Element class uses the `defining_features` list to determine which attributes to copy. Since `tracking_method` wasn't in this list, it wasn't being copied during cloning, causing it to default to `"cheetah"` in the new instance.
> Make sure that the clone method preserves the tracking_method

- CHANGELOG.md
- cheetah/accelerator/screen.py
The vertical screen misalignment was applied to coordinate 1 (i.e. `px`) instead of coordinate 2 (i.e. `y`).
> [WIP] Fix vertical misalignment in screen object

- CHANGELOG.md
- cheetah/accelerator/dipole.py
- tests/test_dipole.py
Adds a variable `gp_safe` in the Bmad-X computations of `Dipole`, which can be used instead of `gp`, when `gp` is zero and would result in a division by zero. `gp_safe` is always at least `1e-12`. `gp` is zero when `angle` is zero.
When setting the `angle` of a `Dipole` and using the `bmadx` tracking method, the resulting output beam is currently full of NaNs.
> Address the fact that `Dipole` with Bmad-X tracking and `angle=0` would produce `NaN`s

- CHANGELOG.md
- cheetah/particles/particle_beam.py
Refer to `self.species` instead of `species`.
`ParticleBeam.from_xyz_pxpypz()` throws an error when `species` is not specified.
> fix a missing self ref

- CHANGELOG.md
- tests/test_space_charge_kick.py
The way the space-charge tests where written was incorrect for the non-relativistic case.
The space-charge tests represents a situation where the beam has the same size in `x`, `y` and `z`, in the beam rest frame. (See Free Expansion of a Cold Uniform Bunch in https://accelconf.web.cern.ch/hb2023/papers/thbp44.pdf.) But since `cheetah` works with the beam duration, we need to correctly calculate the corresponding beam duration. 
There was a missing `beta` factor in the previous formula. This only matters for non-relativistic beams.
> Correct beam duration in space-charge test (only affects non-relativistic case)

- CHANGELOG.md
- cheetah/accelerator/segment.py
Change default resolution of all `Segment` plot functions to `None`, i.e. element-wise.
The previous resolution of `0.01` was needlessly low and made large lattices plot infeasibly slowly.
> Remove small resolution slowing down plot functions

- CHANGELOG.md
- cheetah/particles/particle_beam.py
- tests/test_particle_beam.py
Properly handle the device in `ParticleBeam.randomly_subsampled`.
Closes #439.
> Fix and test device issue with `randomly_subsampled`

- CHANGELOG.md
- cheetah/particles/particle_beam.py
- cheetah/utils/__init__.py
- cheetah/utils/statistics.py
- tests/test_compare_beam_type.py
- tests/test_dipole.py
- tests/test_drift.py
- tests/test_parameter_beam.py
- tests/test_particle_beam.py
- tests/test_quadrupole.py
- tests/test_space_charge_kick.py
- tests/test_speed.py
- tests/test_statistics.py
- tests/test_transverse_deflecting_cavity.py
Rework the covariance computation in `ParticleBeam.as_parameter_beam` to fix an issue that caused the covariance to be computed incorrectly for vectorised beams.
Closes #470.
> Improve the cov calculation in ParticleBeam to alllow batched calculation

- CHANGELOG.md
- cheetah/converters/utils/infix.py
- cheetah/converters/utils/rpn.py
- tests/test_infix.py
- tests/test_rpn.py
Adds the ability to reference vars defined on previous elements in the lattice to RPN and infix expression types.
Required by #498
> Adds key-val lookups in context to rpn and infix

- CHANGELOG.md
- cheetah/accelerator/cavity.py
- tests/test_cavity.py
For cavities with 0 voltage, the numerical issues were already caught. However, the same issue appears for cavities that are fully off-crest in phase, i.e. -90 deg.
- closes #548 
> Ensure inactive `Cavity` do not produce `NaN` in their transfer map

- CHANGELOG.md
- cheetah/accelerator/space_charge_kick.py
- tests/test_space_charge_kick.py
Maintain particle species in `SpaceChargeKick` element.
`SpaceChargeKick` creates new `ParticleBeam` objects but does not preserve the species of the incoming beam. The species defaults to "electron". https://github.com/desy-ml/cheetah/blob/master/cheetah/accelerator/space_charge_kick.py#L584C1-L610C73
Closes #443.
> Maintain particle species in space charge kick
